# Generated by Django 4.1.7 on 2023-02-28 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="capitals",
            name="author",
        ),
    ]
