# Generated by Django 4.1.7 on 2023-02-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0002_remove_capitals_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("healthy", models.CharField(max_length=150)),
                ("max_people", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Capitals",
        ),
    ]
