# Generated by Django 4.1.7 on 2023-03-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0003_restaurants_delete_capitals"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mcdonalds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menu_name", models.CharField(max_length=40)),
            ],
        ),
    ]
