# Generated by Django 4.1.7 on 2023-03-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0005_mcdonalds_name_mcdonalds_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthyFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=40)),
                ("price", models.IntegerField(default=0)),
            ],
        ),
    ]
