# Generated by Django 4.1.7 on 2023-03-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0006_healthyfood"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blinoff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dough", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=40)),
                ("price", models.IntegerField(default=0)),
            ],
        ),
    ]
