# Generated by Django 4.1.7 on 2023-03-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0007_blinoff"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("price", models.IntegerField(default=0)),
            ],
        ),
    ]
