# Generated by Django 4.1.7 on 2023-03-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0008_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blinoff",
            name="name",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="healthyfood",
            name="name",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="mcdonalds",
            name="name",
            field=models.CharField(default="null", max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="restaurants",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
