# Generated by Django 4.1.7 on 2023-03-02 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0009_alter_blinoff_name_alter_healthyfood_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="name",
        ),
        migrations.AddField(
            model_name="order",
            name="count",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="name_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="food.mcdonalds",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blinoff",
            name="price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="healthyfood",
            name="price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="mcdonalds",
            name="price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.IntegerField(),
        ),
    ]
