# Generated by Django 4.1.7 on 2023-03-03 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0010_remove_order_name_order_count_order_name_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Order",
            new_name="McDonaldsOrder",
        ),
    ]
